FROM python:3.13-slim-bookworm@sha256:a569688edb9acf677e8356c3db3eac4b56773e9859f83086d0d580c985cccc9b

RUN pip install mkdocs
RUN pip install mkdocs-material
RUN pip install mkdocs-minify-plugin
RUN pip install mkdocs-redirects
