FROM python:3.13-slim-bookworm@sha256:ae9f9ac89467077ed1efefb6d9042132d28134ba201b2820227d46c9effd3174

RUN pip install mkdocs
RUN pip install mkdocs-material
RUN pip install mkdocs-minify-plugin
RUN pip install mkdocs-redirects
