FROM python:3.13-slim-bookworm@sha256:8f3aba466a471c0ab903dbd7cb979abd4bda370b04789d25440cc90372b50e04

RUN pip install mkdocs
RUN pip install mkdocs-material
RUN pip install mkdocs-minify-plugin
RUN pip install mkdocs-redirects
